### ISSUE TITLE
[TimeLineFragment] Events disappear after a click on "expand"

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android-v2#502] opened 2022-03-17 14:31 UTC
If we are invited in a Room when we click on: "Expand" the events disappear.

https://user-images.githubusercontent.com/15031750/158828522-99092b43-3a1e-4330-b880-34d411c55bf5.mov

**Comment by giomfo** [comment] 2022-03-30 07:55
cannot reproduce in recent rooms
we will close it until we reproduce it in a new room in a recent version of Tchap

**Closed by giomfo** 2022-03-30 07:55 UTC
Labels: bug, android
