### ISSUE TITLE
On external signout the screen isn't personalized

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#440] opened 2022-02-18 17:39 UTC
![image](https://user-images.githubusercontent.com/1238254/154734146-0c7f349a-d3d5-4d67-9b4e-5d31836136cc.png)

How to reproduce :
- Change password on an another device
- The android client is disable

**Comment by giomfo** [comment] 2022-02-21 09:27
We have first to check the role of this screen before customizing it

**Comment by giomfo** [comment] 2022-02-21 09:44
Step 1: test this screen in Element

**Comment by Florian14** [comment] 2022-02-23 14:05
I could not reproduce, for each try, I was redirected to the same logout screen:
![image](https://user-images.githubusercontent.com/11990514/155334445-9f1cd57a-6aaf-470d-9be2-efbb5912ba6a.png)


I tried:
- change the password from the web client, tchap opened in android and logged out by the server
- change the password from the web client, tchap closed in android and logged out by the server after opening the app
- remove the android session from the web client, tchap opened in the android session and logged out by the server

Here is the screen for Tchap:
![image](https://user-images.githubusercontent.com/11990514/155334933-a6ff0f16-b304-4e0f-b7bb-19a61d596b46.png)

**Comment by jdauphant** [comment] 2022-02-23 17:00
My account is also connected with Element Desktop, this could be a difference ?

**Closed** 2022-03-02 18:19 UTC
Labels: bug, enhancement, question, to estimate, design, android
